package com.featureforge.backend.enums;

public enum ActivityType {
    WORKSPACE_CREATED,
    WORKSPACE_RENAMED,

    MEMBER_INVITED,
    MEMBER_REMOVED,
    MEMBER_LEFT,

    INVITATION_ACCEPTED,
    INVITATION_REVOKED,

    FEATURE_CREATED,
    FEATURE_UPDATED,
    FEATURE_DELETED,

    FEATURE_PROMOTED_TO_STAGING,
    FEATURE_QA_ACCEPTED,
    FEATURE_QA_REJECTED,

    FEATURE_APPROVED_FOR_PRODUCTION,
    FEATURE_ACTIVATED_IN_PRODUCTION,
    FEATURE_DEACTIVATED_IN_PRODUCTION,
    FEATURE_ROLLOUT_UPDATED,
    FEATURE_SCHEDULED,

    API_KEY_REGENERATED
}
