import { useOutletContext } from 'react-router-dom'
import { FiToggleRight, FiCode, FiGitPullRequest, FiCheckCircle } from 'react-icons/fi'
import FeatureOverview from '../components/overview/FeatureOverview'
import PendingApprovals from '../components/overview/PendingApprovals'
import RecentActivity from '../components/overview/RecentActivity'
import './Overview.css'

export default function Overview() {
  const { currentWorkspaceName, role } = useOutletContext();
  const activeRole = role || localStorage.getItem('currentWorkspaceRole');

  const featureOverviewMetrics = [
    {
      label: 'Active Features',
      value: '12',
      subcaption: 'Currently enabled',
      icon: <FiToggleRight size={18} />
    },
    {
      label: 'Development',
      value: '4',
      subcaption: 'flags currently in draft',
      icon: <FiCode size={18} />
    },
    {
      label: 'Staging',
      value: '6',
      subcaption: 'flags undergoing testing',
      icon: <FiGitPullRequest size={18} />
    },
    {
      label: 'Production',
      value: '8',
      subcaption: 'live flags serving traffic',
      icon: <FiCheckCircle size={18} />
    }
  ];

  const recentActivities = [
    { title: 'Feature Flag Created', description: 'Beta Rollout created by John Doe', time: '2 hours ago' },
    { title: 'Member Joined Workspace', description: 'Jane Smith accepted invitation', time: '5 hours ago' },
    { title: 'Environment Key Regenerated', description: 'Production key regenerated by John Doe', time: 'Yesterday' }
  ];

  return (
    <div className="overview-page">
      <div className="overview-header">
        <span className="overview-badge">WORKSPACE OVERVIEW</span>
        <h1 className="overview-title">
          {currentWorkspaceName || 'Workspace'}
        </h1>
        <p className="overview-desc">
          Manage environments, feature flag keys, and access logs for this project workspace.
        </p>
      </div>

      {/* Feature Overview Section */}
      <FeatureOverview featureOverviewMetrics={featureOverviewMetrics} />

      {/* Two-Column Grid: QA Approvals and Recent Activity */}
      <div className="dashboard-grid-columns">
        <PendingApprovals activeRole={activeRole} />
        <RecentActivity recentActivities={recentActivities} />
      </div>
    </div>
  );
}
